main: main.java.com.mrunknown404.serdana.Main
name: Serdana
version: 0.0.1
author: -Unknown-
api-version: 1.13

commands:
  setTier:
    description: Sets an item's tier
    usage: "Usage: '/setTier' [tier]"
    permission: serdana.setTier
  serdana:
    aliases: sd
    description: Edits Serdana related values
    usage: "Usage: '/serdana' [argument]"
    permission: serdana.serdanaReload

permissions:
  serdana.setTier:
    default: op
  serdana.serdana:
    default: op