main: main.java.com.mrunknown404.serdana.Main
name: Serdana
version: 0.5.0
author: -Unknown-
api-version: 1.13

commands:
  setTier:
    description: Sets an item's tier
    usage: "Usage: '/setTier' [tier]"
    permission: serdana.setTier
  serdana:
    aliases: sd
    description: Edits Serdana related values
    usage: "Usage: '/serdana' [argument]"
    permission: serdana.serdanaReload
  setBan:
    description: Bans an item
    usage: "Usage: '/setBan'"
    permission: serdana.setBan
  bounty:
    description: Creates/cancels a bounty
    usage: "Usage: '/bounty' [argument] [player]"
    permission: serdana.bounty

permissions:
  serdana.setTier:
    default: op
  serdana.serdana:
    default: op
  serdana.setBan:
    default: op
  serdana.bounty:
    default: true