main: main.java.com.mrunknown404.serdana.Main
name: Serdana
version: 0.7.0
author: -Unknown-
api-version: 1.13

commands:
  setTier:
    description: Sets an item's tier
    usage: "Usage: '/setTier' [tier]"
    permission: serdana.setTier
  serdana:
    aliases: sd
    description: Edits Serdana related values
    usage: "Usage: '/serdana' [argument]"
    permission: serdana.serdanaReload
  setBan:
    description: Bans an item
    usage: "Usage: '/setBan'"
    permission: serdana.setBan
  bounty:
    description: Creates/cancels a bounty
    usage: "Usage: '/bounty' [argument] [player]"
    permission: serdana.bounty
  join:
    description: Creates a fake login message
    usage: "Usage: '/join' [name (optional)]"
    permission: serdana.join
  leave:
    description: Creates a fake logout message
    usage: "Usage: '/leave' [name (optional)]"
    permission: serdana.leave
  showitem:
    description: Shows your held item
    usage: "Usage: '/showitem' must hold an item"
    permission: serdana.showitem
  dots:
    description: ...
    usage: "Usage: '/dots'"
    permission: serdana.dots
  sayas:
    description: Talk as another person
    usage: "Usage: '/sayas [name] [message]'"
    permission: serdana.sayas
  coo:
    description: Coo
    usage: "Usage: '/coo'"
    permission: serdana.coo
  prayer:
    description: Write/get prayers
    usage: "Usage: '/prayer' [argument] [argument]"
    permission: serdana.prayer

permissions:
  serdana.setTier:
    default: op
  serdana.serdana:
    default: op
  serdana.setBan:
    default: op
  serdana.bounty:
    default: true
  serdana.join:
    default: op
  serdana.leave:
    default: op
  serdana.showitem:
    default: true
  serdana.dots:
    default: op
  serdana.sayas:
    default: op
  serdana.coo:
    default: op
  serdana.prayer:
    default: true
  serdana.prayer.send:
    default: true
  serdana.prayer.book:
    default: true
  serdana.prayer.showUnsorted:
    default: op
  serdana.prayer.showGood:
    default: op
  serdana.prayer.showBad:
    default: op
  serdana.prayer.setUnsorted:
    default: op
  serdana.prayer.setGood:
    default: op
  serdana.prayer.setBad:
    default: op